[
default
]
extend-ignore-re = [
    "WNat",
    "WNAT",
    "wNat",
    "bU",
    "whats",
    "requestor",
    "devlop",
    "crate"
]

[
type.md
]
check-file = true
extend-ignore-identifiers-re = [
    "WNat",
    "WNAT",
    "wNat"
]

[
files
]
extend-exclude = [
    "*.svg",
    "*.png",
    "*.jpg",
    "*.woff",
    "*.woff2",
    "*.pdf",
    "package-lock.json"
]