[default.extend-words]
# Custom ignored words
WNat = "WNat"
WNAT = "WNAT"
wNat = "wNat"
bU = "bU"
whats = "whats"
requestor = "requestor"
devlop = "devlop"
crate = "crate"
# Handle mis- prefix words
mis-encoding = "mis-encoding"
ba = "ba"

[files]
# File patterns to exclude
extend-exclude = [
  "*.svg",
  "*.png",
  "*.jpg",
  "*.woff",
  "*.woff2",
  "*.pdf",
  "package-lock.json",
  "*.mod",     # Exclude go.mod files
  "*.sum"      # Exclude go.sum for consistency
]

[default]
check-filename = true
binary = false
ignore-hex = true