[default]
extend-ignore-identifiers-re = ["mis[a-z]+"]
extend-ignore-re = ["mis[a-z]+"]

[default.extend-words]
WNat = "WNat"
WNAT = "WNAT"
wNat = "wNat"
bU = "bU"
whats = "whats"
requestor = "requestor"
devlop = "devlop"
crate = "crate"

[files]
extend-exclude = [
  "*.svg",
  "*.png",
  "*.jpg",
  "*.woff",
  "*.woff2",
  "*.pdf",
  "package-lock.json",
  "*.mod",
  "*.sum"
]