[default]
binary = false

[default.extend-words]
WNat = "WNat"
WNAT = "WNAT"
wNat = "wNat"
bU = "bU"
whats = "whats"
requestor = "requestor"
devlop = "devlop"
crate = "crate"
mis = "mis"

[files]
extend-exclude = [
  "*.svg",
  "*.png",
  "*.jpg",
  "*.woff",
  "*.woff2",
  "*.pdf",
  "package-lock.json",
  "*.mod",
  "*.sum",
  "*.lock"
]