[default.extend-words]
# Custom ignored words
WNat = "WNat"
WNAT = "WNAT"
wNat = "wNat"
bU = "bU"
whats = "whats"
requestor = "requestor"
devlop = "devlop"
crate = "crate"
ba = "ba"
mis = "mis"

[files]
# File patterns to exclude
extend-exclude = [
  "*.svg",
  "*.png",
  "*.jpg",
  "*.woff",
  "*.woff2",
  "*.pdf",
  "package-lock.json"
]

[default]
binary = false
check-filename = true
unicode = true