name: Spell Check

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - "**/*.txt"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.py"
      - "**/*.js"
      - "**/*.tsx"
      - "**/*.html"
      - "**/*.rst"
      - "**/*.go"
      - "!**/*.svg" # Exclude svg files from triggering the workflow
      - "!**/*.sol"
      - "!**/*.sum"
      - "!**/*.mod"
      - "!**/*.json"

permissions:
  contents: read

jobs:
  spell-check:
    if: github.event.pull_request.changed_files > 0
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Spell Check with Typos
        uses: crate-ci/typos@v1.29.4
        with:
          files: .
          config: .github/config/typos.toml
