name: Spell Check
on:
  pull_request:

permissions:
  contents: read

jobs:
  spell-check:
    if: github.event.pull_request.changed_files > 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Spell Check
        uses: crate-ci/typos@master
        with:
          config: ./.github/config/typos.toml