name: Validate PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

# Adding both pull-requests and contents permissions
permissions:
  pull-requests: write
  contents: read
  issues: read

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Adding checkout action explicitly

      - name: Validate PR Title with Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          # Using a different token syntax
          GITHUB_TOKEN: ${{ github.token }}
        with:
          types: |
            feat
            fix
            docs
            chore
            test
            refactor
            ci
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          wip: true
          validateSingleCommit: false
